# Auto-generated by cadlang. Regenerate from the .cad.py description
# Usage: Utilities -> Scripts and Add-Ins -> Scripts -> Create -> From Existing -> this file.

import adsk.core, adsk.fusion, adsk.cam, traceback, math

def run(context):
    ui = None
    try:
        app = adsk.core.Application.get(); ui = app.userInterface
        design = adsk.fusion.Design.cast(app.activeProduct)
        if not design: ui.messageBox("Open a Fusion design first"); return
        design.designType = adsk.fusion.DesignTypes.ParametricDesignType
        root = design.rootComponent; params = design.userParameters

        def P(n, expr, units="mm", comment=""):
            it = params.itemByName(n)
            vi = adsk.core.ValueInput.createByString(f"{expr} {units}")
            if it: it.expression = f"{expr} {units}"
            else: params.add(n, vi, units, comment)

        P('ring_id', 240.5, 'mm')
        P('ring_od', 250.0, 'mm')
        P('ring_h', 46.0, 'mm')
        P('notch_arc', 20.4, 'mm')
        P('notch_depth', 32.0, 'mm')
        P('chamfer_len', 2.0, 'mm')
        P('chamfer_flare', 1.0, 'mm')
        P('hole_dia', 4.0, 'mm')
        P('hole_depth', 4.0, 'mm')
        P('hole_z1', 5.0, 'mm')
        P('hole_z2', 11.667, 'mm')

        # ---- revolve 'base' ----
        sk = root.sketches.add(root.xZConstructionPlane)
        sk.name = 'base_profile'
        _L = sk.sketchCurves.sketchLines
        _P = [adsk.core.Point3D.create(12.125000, 0, 0.000000), adsk.core.Point3D.create(12.500000, 0, 0.000000), adsk.core.Point3D.create(12.500000, 0, 4.600000), adsk.core.Point3D.create(12.025000, 0, 4.600000), adsk.core.Point3D.create(12.025000, 0, 0.200000)]
        for i in range(len(_P)): _L.addByTwoPoints(_P[i], _P[(i+1) % len(_P)])
        prof = sk.profiles.item(0)
        _rI = root.features.revolveFeatures.createInput(prof, root.zConstructionAxis, adsk.fusion.FeatureOperations.NewBodyFeatureOperation)
        _rI.setAngleExtent(False, adsk.core.ValueInput.createByString("360 deg"))
        body = root.features.revolveFeatures.add(_rI).bodies.item(0)
        body.name = 'base'
        # ---- cut 'rail_notches' ----
        _face = None; _zmax = -1e9
        for _fc in body.faces:
            try:
                if abs(_fc.geometry.normal.z) > 0.9 and _fc.centroid.z > _zmax:
                    _zmax = _fc.centroid.z; _face = _fc
            except: pass
        sk = root.sketches.add(_face)
        sk.name = 'rail_notches_sketch'
        _Ln = sk.sketchCurves.sketchLines
        _z  = _face.centroid.z if "_face" in dir() and _face else 0.0
        _rp = [adsk.core.Point3D.create(11.925000,-1.020000,_z), adsk.core.Point3D.create(12.600000,-1.020000,_z), adsk.core.Point3D.create(12.600000,1.020000,_z), adsk.core.Point3D.create(11.925000,1.020000,_z)]
        for _i in range(4): _Ln.addByTwoPoints(_rp[_i], _rp[(_i+1) % 4])
        _profs = adsk.core.ObjectCollection.create()
        for _p in sk.profiles:
            try: _a = _p.areaProperties().area
            except: continue
            if _a < 1.0:  # cm^2  ->  < 100 mm^2
                _profs.add(_p)
        if _profs.count == 0:
            _profs.add(sk.profiles.item(0))
        _eI = root.features.extrudeFeatures.createInput(_profs, adsk.fusion.FeatureOperations.CutFeatureOperation)
        _eI.setDistanceExtent(False, adsk.core.ValueInput.createByString('-notch_depth'))
        _eI.participantBodies = [body]
        _cut = root.features.extrudeFeatures.add(_eI); _cut.name = 'rail_notches'
        _ents = adsk.core.ObjectCollection.create(); _ents.add(_cut)
        _pI = root.features.circularPatternFeatures.createInput(_ents, root.zConstructionAxis)
        _pI.quantity = adsk.core.ValueInput.createByString('4')
        _pI.totalAngle = adsk.core.ValueInput.createByString('360 deg')
        _pI.isSymmetric = False
        root.features.circularPatternFeatures.add(_pI)
        # ---- cut 'heat_inserts' ----
        _cpI = root.constructionPlanes.createInput()
        _cpI.setByOffset(root.yZConstructionPlane, adsk.core.ValueInput.createByReal(12.500000))
        _pl = root.constructionPlanes.add(_cpI); _pl.name = 'heat_inserts_plane'
        sk = root.sketches.add(_pl)
        sk.name = 'heat_inserts_sketch'
        sk.sketchCurves.sketchCircles.addByCenterRadius(adsk.core.Point3D.create(0.000000,0.500000,0), 0.200000)
        sk.sketchCurves.sketchCircles.addByCenterRadius(adsk.core.Point3D.create(0.000000,1.166700,0), 0.200000)
        _profs = adsk.core.ObjectCollection.create()
        for _p in sk.profiles:
            try: _a = _p.areaProperties().area
            except: continue
            if _a < 1.0:  # cm^2  ->  < 100 mm^2
                _profs.add(_p)
        if _profs.count == 0:
            _profs.add(sk.profiles.item(0))
        _eI = root.features.extrudeFeatures.createInput(_profs, adsk.fusion.FeatureOperations.CutFeatureOperation)
        _eI.setDistanceExtent(False, adsk.core.ValueInput.createByString('-hole_depth'))
        _eI.participantBodies = [body]
        _cut = root.features.extrudeFeatures.add(_eI); _cut.name = 'heat_inserts'
        _ents = adsk.core.ObjectCollection.create(); _ents.add(_cut)
        _pI = root.features.circularPatternFeatures.createInput(_ents, root.zConstructionAxis)
        _pI.quantity = adsk.core.ValueInput.createByString('4')
        _pI.totalAngle = adsk.core.ValueInput.createByString('360 deg')
        _pI.isSymmetric = False
        root.features.circularPatternFeatures.add(_pI)

        ui.messageBox("cadlang: DewShieldOverlapRing created")
    except:
        if ui: ui.messageBox(traceback.format_exc())